Flaber started at:<class 'datetime.datetime'>
Labeling conn.log file: ../../../../captures/iot-pcaps/CTU-IoT-Malware-Capture-52-1/bro/conn.log with 19781379 lines 
Exception in labeler function: 'resp_bytes' 
 Exception at row: {'Field': 'resp_bytes', 'bro field number': '9', 'Data': '5000', 'Comparator': 'gt', 'Label': 'FileDownload', 'type': 'Malicious', 'connector': '-'} 
 Exception at flow {'ts': '1552053025.488706', 'uid': 'Cf8Zv41y7EuXP7rzUb', 'id.orig_h': '192.168.1.197', 'id.orig_p': 63420, 'id.resp_h': '25.153.141.59', 'id.resp_p': 23, 'proto': 'tcp', 'service': '', 'conn_state': 'S0', 'local_orig': False, 'local_resp': False, 'missed_bytes': 0, 'history': 'S', 'orig_pkts': 1, 'orig_ip_bytes': 40, 'resp_pkts': 0, 'resp_ip_bytes': 0, 'tunnel_parents': ''} 
 Exception in labeler function: 'resp_bytes' 
 Exception at row: {'Field': 'resp_bytes', 'bro field number': '9', 'Data': '5000', 'Comparator': 'gt', 'Label': 'FileDownload', 'type': 'Malicious', 'connector': '-'} 
 Exception at flow {'ts': '1552079186.193125', 'uid': 'C8xnW640VEFQCZDYge', 'id.orig_h': '192.168.1.197', 'id.orig_p': 63420, 'id.resp_h': '134.42.19.94', 'id.resp_p': 23, 'proto': 'tcp', 'service': '', 'conn_state': 'S0', 'local_orig': False, 'local_resp': False, 'missed_bytes': 0, 'history': 'S', 'orig_pkts': 1, 'orig_ip_bytes': 40, 'resp_pkts': 0, 'resp_ip_bytes': 0, 'tunnel_parents': ''} 
 Exception in labeler function: 'resp_bytes' 
 Exception at row: {'Field': 'resp_bytes', 'bro field number': '9', 'Data': '5000', 'Comparator': 'gt', 'Label': 'FileDownload', 'type': 'Malicious', 'connector': '-'} 
 Exception at flow {'ts': '1552079214.912709', 'uid': 'CaVvuH3eIS3Mddvc4f', 'id.orig_h': '192.168.1.197', 'id.orig_p': 63420, 'id.resp_h': '76.244.49.196', 'id.resp_p': 23, 'proto': 'tcp', 'service': '', 'conn_state': 'S0', 'local_orig': False, 'local_resp': False, 'missed_bytes': 0, 'history': 'S', 'orig_pkts': 1, 'orig_ip_bytes': 40, 'resp_pkts': 0, 'resp_ip_bytes': 0, 'tunnel_parents': ''} 
 Exception in labeler function: 'resp_bytes' 
 Exception at row: {'Field': 'resp_bytes', 'bro field number': '9', 'Data': '5000', 'Comparator': 'gt', 'Label': 'FileDownload', 'type': 'Malicious', 'connector': '-'} 
 Exception at flow {'ts': '1552079339.985614', 'uid': 'CMKB0k3TssqcT4VkT2', 'id.orig_h': '192.168.1.197', 'id.orig_p': 63420, 'id.resp_h': '146.101.129.6', 'id.resp_p': 23, 'proto': 'tcp', 'service': '', 'conn_state': 'S0', 'local_orig': False, 'local_resp': False, 'missed_bytes': 0, 'history': 'S', 'orig_pkts': 1, 'orig_ip_bytes': 40, 'resp_pkts': 0, 'resp_ip_bytes': 0, 'tunnel_parents': ''} 
 Flaber finished at:02/12/19 18:42:46
